# Aiming for 3.4k QPS/node at <200ms latency

# metadata|test:load
benchmarks:
  - cloud_spanner_ycsb:
      flags:
        ycsb_skip_run_stage: True

        cloud_spanner_config: regional-us-west1
        cloud_spanner_nodes: 3

        ycsb_record_count: 100000000
        ycsb_client_vms: 3

        # VMs
        zones: us-west1-b
        machine_type: n1-standard-8
        gce_network_name: default
        ycsb_preload_threads: "320"
        zones: us-west1-b

        # Data size: 1 column per row, row size 1KB, 100GB total size
        ycsb_field_count: 1
        ycsb_field_length: 1000

        ycsb_tar_url: https://storage.googleapis.com/externally_shared_files/ycsb-0.18.0-SNAPSHOT.tar.gz

        ycsb_preload_threads: "320"
        ycsb_measurement_type: hdrhistogram
